import Providers from '@/Components/Providers'
import './globals.css'
import { Inter } from 'next/font/google'
import { User } from '@/lib/types'
import {headers} from 'next/headers'
import { Toaster } from '@/Components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
async function getUser() {
  const Headers = headers()
  const authorization = Headers.get("authorization");
  const cookie = Headers.get("cookie");
  const response = await fetch(`${process.env.NEXT_PUBLIC_SERVER_DOMAIN}/me`, {
    credentials: "include",
    //@ts-ignore
    headers: {
      "Content-type": "application/json",
      authorization,
      cookie
    }
  })
  const user = await response.json()
  if (response.ok) {
    return user as User
  }
  return null
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {

const user = await getUser()
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Providers user={user}>
        <body className={inter.className}>{children}</body>
        <Toaster />
      </Providers>
    </html>
  );
}
