import Providers from '@/Components/Providers'
import './globals.css'
import { Inter } from 'next/font/google'

import { Toaster } from '@/Components/ui/toaster'
import { getUser } from '@/lib/serverFunctions'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {

const user = await getUser()
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Providers user={user}>
        <body className={inter.className}>{children}</body>
        <Toaster />
      </Providers>
    </html>
  );
}
